// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/a_d/PlasmicGlobalContextsProvider";
import { ScreenVariantProvider } from "../components/plasmic/a_d/PlasmicGlobalVariant__Screen";
import { PlasmicInscricao } from "../components/plasmic/a_d/PlasmicInscricao";
import { useRouter } from "next/router";

function Inscricao() {
  return (
    <GlobalContextsProvider>
      <ph.PageParamsProvider
        params={useRouter()?.query}
        query={useRouter()?.query}
      >
        <PlasmicInscricao 
          form={{
            onKeyPress: (event) => {
                if (event.key === "Enter") {
                  event.preventDefault();
                }
            }
          }}
          endpoint={process.env.ENDPOINT!}
        />
      </ph.PageParamsProvider>
    </GlobalContextsProvider>
  );
}

export default Inscricao;
