// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/a_d_2/PlasmicGlobalContextsProvider";
import { PlasmicInscricao } from "../components/plasmic/a_d_2/PlasmicInscricao";
import { useRouter } from "next/router";
import { validate } from "email-validator";

function InscricaoSV() {
  return (
    <GlobalContextsProvider>
      <ph.PageParamsProvider
        params={useRouter()?.query}
        query={useRouter()?.query}
      >
        <PlasmicInscricao
          form={{
            onKeyPress: (event) => {
                if (event.key === "Enter") {
                  event.preventDefault();
                }
            }
          }}
          endpoint={process.env.NEXT_PUBLIC_ENDPOINT!}
          adultPrice={90}
          kidsPrice={30}
          isInternal={true}
          isSv={true}
          emailValidator={validate}
        />
      </ph.PageParamsProvider>
    </GlobalContextsProvider>
  );
}

export default InscricaoSV;
